//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4927
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSUTools.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSUTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Auto Compress &amp;Screenshot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompressScreenshot {
            get {
                return ResourceManager.GetString("AutoCompressScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Auto Restore Window Position and Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoRestoreWindowPositionAndSize {
            get {
                return ResourceManager.GetString("AutoRestoreWindowPositionAndSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Chat Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChatLog {
            get {
                return ResourceManager.GetString("ChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable Wi&amp;ndow Resizing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisableWindowResizing {
            get {
                return ResourceManager.GetString("DisableWindowResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExecutionFailed {
            get {
                return ResourceManager.GetString("ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E&amp;xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open &amp;Log Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenLogFolder {
            get {
                return ResourceManager.GetString("OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Scr&amp;eenshot Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenScreenshotFolder {
            get {
                return ResourceManager.GetString("OpenScreenshotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Restore Window Position and Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestoreWindowPositionAndSize {
            get {
                return ResourceManager.GetString("RestoreWindowPositionAndSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sa&amp;ve Window Position and Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveWindowPositionAndSize {
            get {
                return ResourceManager.GetString("SaveWindowPositionAndSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show System &amp;Buttons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowSystemButtons {
            get {
                return ResourceManager.GetString("ShowSystemButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowNotFound {
            get {
                return ResourceManager.GetString("WindowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window operation failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowOperationFailed {
            get {
                return ResourceManager.GetString("WindowOperationFailed", resourceCulture);
            }
        }
    }
}
